spring:
  application:
    name: TOYDETAILS
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    platform: h2
    schema: classpath:sql/schema-h2.sql
    data: classpath:sql/data-h2.sql
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true

info:
  build:
    version: 12.4.2
    projectName: ToyDetails
server:
  servlet:
    contextPath: /toy-details
  port: 8080
  ssl:
    enabled: false

springfox:
 documentation:
   swagger:
     v2:
         path: /api-docs
---